classdef FullImageSampler < ImageSampler
%FULLIMAGESAMPLER Samples all elements of an image
%
%   output = FullImageSampler(input)
%
%   Example
%   FullImageSampler
%
%   See also
%
%
% ------
% Author: David Legland
% e-mail: david.legland@grignon.inra.fr
% Created: 2011-07-20,    using Matlab 7.9.0.529 (R2009b)
% Copyright 2011 INRA - Cepia Software Platform.

%% Properties
properties
    % the base image
    image;
end


%% Static factory
methods (Static = true)
    function sampler = create(image)
        sampler = FullImageSampler(image);
    end
end


%% Constructor
methods
    function this = FullImageSampler(varargin)
        
        if nargin < 1
            return;
        end
        
        var = varargin{1};
        if isa(var, 'Image')
            % initialisation constructor
            this.image = var;
            
        elseif isa(var, 'FullImageSampler')
            % copy constructor
            this.image = var.image;
            
        end
        
    end
end


%% General methods
methods
    function n = positionNumber(this)
        % Number of positions generated by this sampler
        n = prod(size(this.image)); %#ok<PSIZE>
    end
    
    function points = positions(this)
        % Return the array of sampled positions
        
        nd = this.image.dimension;
        if nd == 2
            lx = xData(this.image);
            ly = yData(this.image);
            [x y] = meshgrid(lx, ly);
            points = [x(:) y(:)];
            
        elseif nd == 3
            lx = xData(this.image);
            ly = yData(this.image);
            lz = zData(this.image);
            [x y z] = meshgrid(lx, ly, lz);
            points = [x(:) y(:) z(:)];
            
        else
            error('Not implemented for this dimension');
        end
    end
    
end

end