classdef FullImageSampler < ImageSampler
%FULLIMAGESAMPLER Samples all elements of an image.
%
%   output = FullImageSampler(input)
%
%   Example
%   FullImageSampler
%
%   See also
%

% ------
% Author: David Legland
% e-mail: david.legland@inra.fr
% Created: 2011-07-20,    using Matlab 7.9.0.529 (R2009b)
% Copyright 2011 INRA - Cepia Software Platform.

%% Properties
properties
    % the base image
    Image;
end


%% Static factory
methods (Static = true)
    function sampler = create(image)
        sampler = FullImageSampler(image);
    end
end


%% Constructor
methods
    function obj = FullImageSampler(varargin)
        
        if nargin < 1
            return;
        end
        
        var = varargin{1};
        if isa(var, 'Image')
            % initialisation constructor
            obj.Image = var;
            
        elseif isa(var, 'FullImageSampler')
            % copy constructor
            obj.Image = var.Image;
            
        end
        
    end
end


%% General methods
methods
    function n = positionNumber(obj)
        % Number of positions generated by obj sampler
        n = prod(size(obj.Image)); %#ok<PSIZE>
    end
    
    function points = positions(obj)
        % Return the array of sampled positions
        
        nd = ndims(obj.Image);
        if nd == 2
            lx = xData(obj.Image);
            ly = yData(obj.Image);
            [x, y] = meshgrid(lx, ly);
            points = [x(:) y(:)];
            
        elseif nd == 3
            lx = xData(obj.Image);
            ly = yData(obj.Image);
            lz = zData(obj.Image);
            [x, y, z] = meshgrid(lx, ly, lz);
            points = [x(:) y(:) z(:)];
            
        else
            error('Not implemented for obj dimension');
        end
    end
    
end

end