classdef GridImageSampler < ImageSampler
%GRIDIMAGESAMPLER Samples elements along a subgrid in image
%
%   output = GridImageSampler(input)
%
%   Example
%   GridImageSampler
%
%   See also
%

% ------
% Author: David Legland
% e-mail: david.legland@inra.fr
% Created: 2011-07-20,    using Matlab 7.9.0.529 (R2009b)
% Copyright 2011 INRA - Cepia Software Platform.

%% Properties
properties
    % the base image
    image;
    
    % the steps in each dimension
    steps;
end


%% Static factory
methods (Static = true)
    function sampler = create(image, steps)
        sampler = GridImageSampler(image, steps);
    end
end


%% Constructor
methods
    function this = GridImageSampler(varargin)
        
        if nargin < 1
            return;
        end
        
        var = varargin{1};
        if isa(var, 'Image')
            % initialisation constructor
            this.image = var;
            this.steps = varargin{2};
            
        elseif isa(var, 'GridImageSampler')
            % copy constructor
            this.image = var.image;
            
        end
        
    end
end


%% General methods
methods
    function n = positionNumber(this)
        % Number of positions generated by this sampler
        n = prod(size(this.image)); %#ok<PSIZE>
    end
    
    function points = positions(this)
        % Return the array of sampled positions
        
        lx = xData(this.image);
        lx = lx(1:this.steps(1):end);
        ly = yData(this.image);
        ly = ly(1:this.steps(2):end);
        
        nd = this.image.dimension;
        if nd == 2
            [x, y] = meshgrid(lx, ly);
            points = [x(:) y(:)];
            
        elseif nd == 3
            lz = zData(this.image);
            lz = lz(1:this.steps(3):end);

            [x, y, z] = meshgrid(lx, ly, lz);
            points = [x(:) y(:) z(:)];
            
        else
            error(['Not implemented for dimension ' num2str(nd)]);
        end
    end
    
end

end